# Generated by Django 4.2.1 on 2023-06-01 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_scores_is_adult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scores',
            name='is_adult',
        ),
    ]
